- hosts: node02
  tasks:
    - name: Print all ec2 variables
      debug: var=hostvars[inventory_hostname]

    - name: Get the IP address of ec2 instance
      debug: var=hostvars[inventory_hostname].ansible_all_ipv4_addresses[0]