---
- hosts: node02
  vars_prompt:
    - name: variable
      prompt: "Please enter a variable name"
  tasks:
    - debug:
        msg: "You entered {{ variable }}"
    
    - name: Creating username from the user inut
      become: yes
      user:
        name: "{{ variable }}"

    - debug:
        msg: "{{ variable }} as user is created"

    - name: Create a file if it does not exist
      file:
        path: /home/ec2-user/{{ variable }}
        state: touch
        mode: '0644'
    

