---
- hosts: node02
  tasks:
    - name: Create a folders if it does not exist
      file:
       path: /home/ec2-user/{{ item }}
       state: directory
      with_items:
        - yelp
        - google
        - apple
        - yahoo
        - allstate
        