---
- hosts: node02
  name: Installing packages on webservers using with_items and yum package
  tasks:
    - name: Use of with_items here
      become: yes
      yum:
       name: "{{ item }}"
       state: present
      with_items:
        - mlocate
        - strace
        - java-1.8.0-openjdk
        #- php5
